spring.application.name=AI_Agent

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${API_KEY}

spring.ai.openai.chat.model=openrouter/free
spring.ai.openai.chat.max-tokens=300
weather.api.key=${WEATHER_API_KEY}